FROM golang:1.21-alpine AS builder
LABEL maintainer="nekohasekai <contact-git@sekai.icu>"
RUN apk add --no-cache git
RUN git clone -b sniff-override-rules https://github.com/PuerNya/sing-box.git \
    && mkdir -p /go/src/github.com/sagernet/sing-box  \ 
    && cp -r ./sing-box/* /go/src/github.com/sagernet/sing-box 
    
WORKDIR /go/src/github.com/sagernet/sing-box
ARG GOPROXY=""
ENV GOPROXY ${GOPROXY}
ENV CGO_ENABLED=0
RUN set -ex \
    && apk add build-base \
    && export COMMIT=$(git rev-parse --short HEAD) \
    && export VERSION=$(go run ./cmd/internal/read_tag) \
    && go build -v -trimpath -tags with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api,with_acme \
        -o /go/bin/sing-box \
        -ldflags "-X \"github.com/sagernet/sing-box/constant.Version=$VERSION\" -s -w -buildid=" \
        ./cmd/sing-box
FROM node:18-alpine AS dist
LABEL maintainer="nekohasekai <contact-git@sekai.icu>"
ENV TZ=Asia/Shanghai
ENV IP_ADDRESS=localhost
WORKDIR /singBox
RUN set -ex \
    && apk upgrade \
    && apk add --no-cache procps bash tzdata ca-certificates \
    && rm -rf /var/cache/apk/* 
COPY ./ /singBox
COPY --from=builder /go/bin/sing-box /singBox/singBox
RUN chmod +x /singBox/singBox \
    && rm -rf /singBox/sing-box

COPY . /singBox
cmd ["node", "bundle"]